apiVersion: v1
kind: ConfigMap
metadata:
        name: mysql
        labels:
                app: mysql
data:
        primary.cnf: |
                [mysqlid]
                log-bin
        replica.cnf: |
                [mysqld]
                super-read-only


